### ISSUE TITLE
using cURL - an error occurs

### ISSUE THREAD

**Issue by Andy8912** [Lanjelin/hue-batch#4]
Hi, I wondered if you could help me fix this. 
I wanted to use your hue-batch to switch on my hue lights when my security camera detects movement.
I cant seem to find cURL 7.43 at the link provided only the latest version which is now 7.58.0 
http://www.paehl.com/open_source/?download=curl_758_0_ssl.zip
am i using the correct version? the bat file runs but cant find the bridge IP address so fails

if you can help that would be appreciated 

AH

**Comment by Lanjelin** [comment]
Hi there,
Due to moving, I currently don't have access to test the script against my own hue.
If you've downloaded the newest version of cURL with SSL support, aswell as grabbed the [OPENSSL dlls](http://www.paehl.com/open_source/?download=libssl.zip), and placed them in the same directory as the script, everything should work.

What's returned to you if you open the url https://www.meethue.com/api/nupnp in a webbrowser?

As a bypass, you could replace line 8 and 9 with 
**set _hueip="192.168.1.123"**   :: IP of bridge
If you know the ip of the bridge.

Reply with your findings, I'll attempt to locate and hook up my own bridge meanwhile.

Lanjelin

**Comment by Andy8912** [comment]
Hi thanks for replying
https://www.meethue.com/api/nupnp in a webbrowser wants to download a file nupnp.json
the bridge ip on my network is 10.89.120.6
if I replace line 8 and 9 with set _hueip="10.89.120.6" i still cant get this to work

Thanks 

AH

**Comment by Andy8912** [comment]
Update!!
I added the file nupnp.json to the folder and downloaded  OPENSSL dlls again from the link in your message and suddenly all is working not sure which fixed it but I'm leaving it alone now
Can you advise what command i need to uses to have the lights switch off after a preset time ie 15mins?
my camera now switches them on but not off and there's no provision to send another command 

AH

**Comment by Lanjelin** [comment]
I'm keeping a thumb on the dlls, though if you quite recently set up the hue, there could be a delay here preventing the script from getting the correct IP.
If you open the URL with any other browser than a microsoft product, it should let you read the local address of your bridge in the browser.

For delays, I've been using **ping 1.1.1.1 -n 1 -w %delay%>nul**
where %delay% is time in milliseconds, so **ping 1.1.1.1 -n 1 -w 900000>nul** for 15minutes
I've noticed Win10 seems to have a timeout function though, that I suppose is more accurate.
The equivalent here would be **TIMEOUT /T 900 /NOBREAK** (time in seconds)

**Comment by Andy8912** [comment]
Please excuse my ignorance 
I'm using
hue.bat -k secretkey -l "2 5" -on true
to turn the lights on then for a delay off of 15 mins i would change it to
hue.bat -k secretkey -l "2 5" -on true ping 1.1.1.1 -n 1 -w 900000>nul

Cheers

**Comment by Lanjelin** [comment]
Make a new .bat file, eg runme.bat

```batch
@echo off&cls
hue.bat -k secretkey -l "2 5" -on true
echo Lights are on, waiting 15minutes
ping 1.1.1.1 -n 1 -w 900000>nul
hue.bat -k secretkey -l "2 5" -on false
exit
```
